added short_id and url_photo
exxamalte/python-georss-ingv-centro-nazionale-terremoti-client pull request #1
Opened 2020-05-29 19:47 UTC by caiosweet

Hi. I'm not a developer, but I propose this change. I have been using this system in Homeassistant for more than a year, copying your work from the ign_sismologia component.
I'd like to see your work integrated into homeassistant. Thanks for the attention.

[Here are the changes for homeassistant](
https://github.com/caiosweet/Package-Natural-Events/tree/caiosweet-patch-1/config/custom_components/ingv_centro_nazionale_terremoti)

Other types of images and urls
```
      [PGA](http://shakemap.rm.ingv.it/shake/f"{short_id}"/download/pga.jpg)
      [PGV](http://shakemap.rm.ingv.it/shake/f"{short_id}"/download/pgv.jpg)
      [TvMap](http://shakemap.rm.ingv.it/shake/f"{short_id}"/download/tvmap.jpg)
      [TvMap2](http://shakemap.rm.ingv.it/shake/f"{short_id}"/download/tvmap_bare.jpg)
```

2020-05-30 04:58 UTC, exxamalte commented
Thank you very much for your contribution.
Could you please also add unit tests for the additional functionality?

2020-05-30 05:05 UTC, exxamalte requested changes

2020-05-30 05:05 UTC, exxamalte commented on georss_ingv_centro_nazionale_terremoti_client/__init__.py
> +    def short_id(self) -> Optional[int]:
Should we call this `event_id` because that's how it's called in the source.

2020-05-30 05:05 UTC, exxamalte commented on georss_ingv_centro_nazionale_terremoti_client/__init__.py
> +REGEXP_ATTR_SHORT_ID = r'eventId=(?P<{}>\d+)$'\
`REGEXP_ATTR_EVENT_ID`

2020-05-30 11:48 UTC, caiosweet commented on georss_ingv_centro_nazionale_terremoti_client/__init__.py
> +    def short_id(self) -> Optional[int]:
Okay, I'll try

2020-05-30 12:05 UTC, caiosweet commented
> Thank you very much for your contribution.
> Could you please also add unit tests for the additional functionality?

I did not understand correctly, you mean automation and images? :0)

I also changed in this file [geo_location.py](https://github.com/caiosweet/Package-Natural-Events/blob/9ba43bd8ac0b537668a784e878814b75d3d362eb/config/custom_components/ingv_centro_nazionale_terremoti/geo_location.py)

2020-05-31 02:34 UTC, exxamalte commented
> I did not understand correctly, you mean automation and images? :0)

I meant unit tests like you can find in the `tests` folder. These test ensure that any change in the original code is automatically tested.
If you've never done that before, that's fine. I'll take a look at adding tests then.

2020-05-31 05:42 UTC, caiosweet commented
Never done that before. I’m sorry. 😅

2020-06-24 16:32 UTC, merged